#!/bin/sh

# TJC Help Command

tjc_help() {
  printf 'TJC (Termux Jules CLI) v2.0.0\n\n'
  printf 'Usage:\n  tjc <command> [options]\n\n'
  printf 'Core Commands:\n'
  printf '  help, -h, --help                 Display this help menu\n'
  printf '  version, -v, --version           Display version information\n\n'
  printf 'Job Commands:\n'
  printf '  job create <id> [description]    Create a persistent Job\n'
  printf '  job list                         List stored Jobs\n'
  printf '  job show <id>                    Display a Job record\n'
  printf '  job status <id>                  Display Job status\n'
  printf '  job cancel <id>                  Cancel an active Job\n'
  printf '  job retry <id>                   Retry a failed Job\n\n'
  printf 'Workflow Commands:\n'
  printf '  workflow validate <file>         Validate a workflow\n'
  printf '  workflow run <file>              Execute a workflow\n'
  printf '  workflow resume <report>         Resume a workflow\n'
  printf '  workflow list                    List workflow reports\n'
  printf '  workflow show <report>            Display a workflow report\n\n'
  printf 'Queue Commands:\n'
  printf '  queue add <file> [priority] [id] Queue a workflow\n'
  printf '  queue list                       List queued work\n'
  printf '  queue remove <id>                Remove queued work\n'
  printf '  queue run [workers]              Run bounded workers\n\n'
  printf 'Plugin Commands:\n'
  printf '  plugin list                      List installed plugins\n'
  printf '  plugin show <name>               Display a plugin manifest\n'
  printf '  plugin install <directory>       Install a local plugin\n'
  printf '  plugin run <name> [args...]      Run a policy-approved plugin\n\n'
  printf 'MCP Commands:\n'
  printf '  mcp serve                         Run local stdio MCP server\n\n'
  printf 'Policy Commands:\n'
  printf '  policy init                       Create default policy\n'
  printf '  policy show                       Display policy\n'
  printf '  policy check <operation>          Check an authorization decision\n\n'
  printf 'Observability Commands:\n'
  printf '  audit list                        List structured audit events\n'
  printf '  audit tail [count]                Show recent audit events\n'
  printf '  logs tail [count]                 Show recent human-readable logs\n\n'
  printf 'Scheduler Commands:\n'
  printf '  schedule add <id> <file> [expr]  Register a workflow schedule\n'
  printf '  schedule list                    List active scheduled jobs\n'
  printf '  schedule remove <id>             Unregister a scheduled job\n'
  printf '  schedule run [id]                Trigger scheduled job(s) immediately\n'
  printf '  schedule run-pending             Execute pending due schedules\n'
  printf '  schedule history <id>            Show schedule execution records\n'
  return 0
}
